### ISSUE TITLE
Tesla Used Checklist

### ISSUE THREAD

**Issue by Geczy** [Lunars/tesla#11]
# Used Vehicle Qualification 

- [ ] Vehicle has less than 100k miles (160k kilometers) 
- [ ] No previous or current evidence of accident history 
- [ ] No open mandatory recalls for the VIN 
- [ ] No evidence of current or past aftermarket mechanical modification 
- [ ] No evidence of structural repairs 
- [ ] Air bag light is not illuminated 

# Vehicle Operation 

## Operation

- [ ] Brake Fluid Level 
- [ ] Brake Lights  
- [ ] Defroster — Front, Rear 
- [ ] Emergency Releases 
- [ ] Hazard Lights  
- [ ] Headlights (High and Low Beams)* 
- [ ] Horn Operation 
- [ ] License Plate Lights 
- [ ] Manual Release Cables — Trunk, Frunk 
- [ ] Manual Release Cables — Door (Model 3)  
- [ ] Reverse Light(s)  
- [ ] Seat Belts Retractors— Extend / Retract freely  
- [ ] Seat Buckles— latch and unlatch correctly  
- [ ] Seat Belts — Do not have any mutilations (stain, fraying, cuts, etc.)  
- [ ] Visually inspect all areas that contain an air bag for signs of mutilation. 
- [ ] Tail Lights 
- [ ] Turn Signals (Front, Rear. Side) 
- [ ] One Functional Keys / Cards Present 
- [ ] All Mirrors functional (side-view and rear-view) 
- [ ] Windshield Wiper Operation  
- [ ] Windshield Wiper Fluid top-up (if necessary) 
- [ ] Windshield — No damage in the driver's viewing area, airbag impact area, forward camera viewing area, or within 50 mm of the edge 
- [ ] Windshield — No more than 3 cracks or chips to the glass

## Micellaneous 

- [ ] Park/Neutral/Drive/Reverse Shifting 
- [ ] Steering Column Adjustment  
- [ ] Touchscreen Functionality 
- [ ] Window, door, trunk operations 
- [ ] Driver s door handle
- [ ] Driver's seat functionality  
- [ ] 2nd and 3rd row (if equipped) seats 
- [ ] Pedals are not obstructed  

## Charging

- [ ] Verify vehicle can charge 

# Road Test 

## 3 mile road test 

- [ ] Suspension / Alignment performance 
- [ ] Ride height  adjustment features* 
- [ ] Steering 
- [ ] Brakes  
- [ ] Driver Assistance * 
- [ ] Parking Brake 

# Mechanical 

## Breaks & Rotors

- [ ] Front Rotors Overall Condition 
- [ ] Front Brake Pads > 4.8 mm 
- [ ] Rear Rotors - Overall Condition  
- [ ] Rear Brake Pads > 4.8 mm 
- [ ] Park Brake Pads > 3 mm 
- [ ] Brake Hose Condition 

## Chassis & Suspension

- [ ] Steering Components  
- [ ] Battery Enclosure 

## Tires (Tread Depth 3.2 mm 4/32 in minimum)

- [ ] Front Tire Condition 
- [ ] Rear Tire Condition  
- [ ] LHF Tread: Outer/Center/Inner 
- [ ] LHR Tread: Outer/Center/Inner 
- [ ] RHF Tread Outer/Center/Inner 
- [ ] RHR Tread: Outer/Center/Inner 
- [ ] No Uneven Wear or Sidewall Cracking 
- [ ] No Road Hazard Damage on Wheels and Tires 
- [ ] Tire Pressure (check sticker in driver's side door jamb)  

## Wheels 

- [ ] Correct Lug Nuts Fitted (All)  
- [ ] LHF Wheel Lug Torque (175 Nm)  
- [ ] LHR Wheel Lug Torque (175 Nm)  
- [ ] RHF Wheel Lug Torque (175 Nm)  
- [ ] RHR Wheel Lug Torque (175 Nm) 

# Labels 

- [ ] First Responder Cut Label (First Responder Loop)  
- [ ] First Responder Label (RH Frunk Trim) 
- [ ] Manufacturing Certification Label (B-Pillar) 
- [ ] Refrigerant Label (RH Frunk Trim)  
- [ ] Third Row Seat Label (Model S only: Third Row Seat)* 
- [ ] Tire & Loading Information (US and Canada only: Driver side B-Pillar)  
- [ ] Vehicle Emissions Label (North America only: Lower Liftgate -Trim)  
- [ ] VIN Identification — identical in each location: touchscreen. windshield, Certification label YIN scribe (stamping on the chassis) 

# Post Inspection

## Standard Work

- [ ] Verify that factory reset has already been performed 
- [ ] Inspect charge cables/adapters: 14-50 (1014324-00-E or higher) / J1772 (Rev B or higher), make sure that the are with the vehicle 
- [ ] "Buyers Guide" and completed inspection form included with vehicle 
- [ ] Perform simple exterior wash, vacuum, and remove any debris from the interior of the cabin. 
- [ ] Upload this signed document and attach to the Repair Order.

**Comment by Geczy** [comment]
https://github.com/Lunars/tesla/wiki/Used-Tesla-Checklist
